name: auto_paginated_view
description: "A Flutter package that simplifies implementing infinite scrolling lists with automatic pagination handling."
version: 1.3.0
homepage: https://github.com/CodingFries/auto_paginated_view

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# No assets or fonts needed for this package

# Additional information for pub.dev
repository: https://github.com/CodingFries/auto_paginated_view
issue_tracker: https://github.com/CodingFries/auto_paginated_view/issues
documentation: https://github.com/CodingFries/auto_paginated_view

topics:
  - infinite-scrolling
  - pagination
  - lazy-loading
